//! AccessRequestEntity - Access request and verification
//!
//! Manages data access requests and EVM verification (Phase 2).
//! Central to access control and permission validation.

use serde::{Deserialize, Serialize};

/// Access request entity - Data access request and verification
///
/// Created in Phase 2, goes through EVM verification to proceed to Phase 3
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccessRequestEntity {
    /// Request identifier
    pub request_id: String,

    /// Target data ID
    pub target_data_id: String,

    /// Target secret ID
    pub target_secret_id: String,

    /// Requester process ID (R-Proc)
    pub requester_process_id: String,

    /// Accessor's public key (pkA)
    pub accessor_public_key: Vec<u8>,

    /// Data owner public key (pkO)
    pub owner_public_key: Vec<u8>,

    /// EVM verification result
    pub evm_verification: EvmVerificationData,

    /// ProofPkg information (generated by elciao)
    pub proof_pkg: Option<ProofPkgData>,

    /// Request status
    /// Values: "pending", "evm_verified", "approved", "rejected", "completed"
    pub status: String,

    /// Request creation timestamp
    pub created_at: u64,

    /// EVM verification completion timestamp
    pub evm_verified_at: Option<u64>,

    /// Request completion timestamp
    pub completed_at: Option<u64>,

    /// Timeout timestamp
    pub timeout_at: u64,

    /// Version
    pub version: u64,
}

/// EVM verification data
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EvmVerificationData {
    /// EVM transaction hash
    pub tx_hash: String,

    /// Smart contract address
    pub contract_address: String,

    /// VerificationOK event data
    pub verification_event: Vec<u8>,

    /// Block height
    pub block_height: u64,

    /// Verification timestamp
    pub verified_at: u64,
}

/// ProofPkg data - Verification package by elciao
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProofPkgData {
    /// ProofPkg identifier
    pub proof_pkg_id: String,

    /// Proof package (BlockHeader + Receipt + pkA)
    pub proof_package: Vec<u8>,

    /// Creation timestamp by elciao
    pub created_at: u64,

    /// Verified flag
    pub verified: bool,
}
