//! CFragRepository trait definition
//!
//! Repository interface for CFrag entity persistence operations.

use async_trait::async_trait;

use crate::domain::entities::CFrag;
use crate::domain::errors::DomainResult;
use crate::domain::value_objects::{CFragId, KFragId, SecretId};

use super::Repository;

/// Repository interface for CFrag entity
///
/// CFrag (Cipher Fragment) contains sensitive re-encrypted cryptographic material
/// and implements Zeroize + ZeroizeOnDrop for secure memory handling. CFrags are
/// generated by Holder-Processes during re-encryption and collected by Requester-Processes.
#[async_trait]
pub trait CFragRepository: Repository<CFrag, CFragId> {
    /// Find all CFrags associated with a Secret
    ///
    /// Returns all CFrags for the given SecretId.
    async fn find_by_secret_id(&self, secret_id: &SecretId) -> DomainResult<Vec<CFrag>>;

    /// Find CFrag by its source KFrag ID
    ///
    /// Returns the CFrag generated from a specific KFrag.
    async fn find_by_kfrag_id(&self, kfrag_id: &KFragId) -> DomainResult<Option<CFrag>>;

    /// Delete all CFrags associated with a Secret
    ///
    /// Bulk deletion for cleanup when a Secret is revoked or access expires.
    async fn delete_by_secret_id(&self, secret_id: &SecretId) -> DomainResult<()>;

    /// Count CFrags associated with a Secret
    ///
    /// Useful for checking threshold completion (k of n CFrags collected).
    async fn count_by_secret_id(&self, secret_id: &SecretId) -> DomainResult<usize>;
}
