[package]
name = "contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.0.0-beta8", features = ["staking"] }
cosmwasm-schema = "1.0.0-beta8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = "1.0"
cw-storage-plus = "0.13.4"
thiserror = "1"
zeroize = { version = "1.6", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
bincode = { version = "1.3", default-features = false }
umbral-pre = { version = "0.11", features = ["serde", "default-serialization"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
cw-multi-test = "0.13.4"
